### ISSUE TITLE
govendor update & list is slow

### ISSUE THREAD

**Issue by cep21** [kardianos/govendor#63]
After doing a ```go get -u github.com/kardianos/govendor```

Running it with strace shows it repeatedly reading from files inside the ./vendor directory

This is a somewhat large repository, but not *this* large!

```
> go version
go version go1.5.1 darwin/amd64
16:46:37 (master) jack@Jacks-MacBook-Pro.local:~/.go/src/github.com/signalfx/xyz
< go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jack/.go"
GORACE=""
GOROOT="/opt/boxen/go"
GOTOOLDIR="/opt/boxen/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
16:46:38 (master) jack@Jacks-MacBook-Pro.local:~/.go/src/github.com/signalfx/xyz
< time govendor list +ext
real	1m30.624s
user	2m6.234s
sys	0m6.496s

```

**Comment by kardianos** [comment]
Yeah, That does appear to be a bit excessive. Probably it is just re-reading files when it needs to just look at cache.

**Comment by cep21** [comment]
We're also having trouble using ```govendor update```.  It will also run for a very long time then end without actually updating any code.  The only way we currently have to update code is ```rm -rf vendor && govendor init && govendor add +ext```.  It's very disappointing and reproducible on multiple macs, but on our private repository.  There is no verbose log option for govendor so I don't have any information on why update isn't working.

**Comment by kardianos** [comment]
Eep. I'll profile.

**Comment by kardianos** [comment]
Fixed in a0adb8be6318afff204a39a67c04c4d41087a810 and 5c6a5e5fca6d1c7a5f5bd51bacdd4435472e23b7 .

**Comment by maxtaco** [comment]
We admittedly haven't done any profiling, but are experiencing tons of lag (100s on a fast modern machine with an SSD) in https://github.com/keybase/client/go whenever we run `govendor update`.  It works fast on smaller repos, so something feels quadratic in the size of the repo. This of course with the most recent version.  Anyone else still seeing slowness in large repositories?
